### ISSUE TITLE
comments ?

### ISSUE THREAD

**Issue by liuzhongjun** [cbracco/html5-test-page#2]
It'll be great to add also comments to essential parts of the file ?

**Comment by cbracco** [comment]
Feel free to submit a pull request!

**Comment by liuzhongjun** [comment]
My English is rubbish, but I can read. Anyway this is a very good idea and your project has been very useful for me. I'll think about it.

**Comment by cbracco** [comment]
Closing this one out. If I get some time I will add comments!
