### ISSUE TITLE
Used this to test needed dark mode settings

### ISSUE THREAD

**Issue by greggman** [cbracco/html5-test-page#26]
Thanks for this!!!

Just passing this on. I used this to test what's the minimal set of CSS settings need to handle all html elements in dark mode.

At least on this page [this is what was needed](https://github.com/greggman/html5-test-page/blob/master/dark.css)

You can test [here](https://greggman.github.io/html5-test-page/) and toggle your preference in your devtools (in Chrome Devtools->Settings->Preferences->Rendering->Emulate CSS media feature prefers-color-scheme.

**Comment by cbracco** [comment]
That’s cool! It is outside the scope of this project though, so closing out this issue.
