### ISSUE TITLE
Invalid markup

### ISSUE THREAD

**Issue by ghost** [cbracco/html5-test-page#4]
A HTML5 Test Page is very usefully, i think. But please check the markup. 

![image](https://cloud.githubusercontent.com/assets/9152502/7607786/87371b3c-f964-11e4-859e-68417f393cfb.png)

**Comment by cbracco** [comment]
@svenjuhnke as of [0.2.2](https://github.com/cbracco/html5-test-page/releases/tag/0.2.2), this file now passes the validation test.
![screenshot 2015-05-13 10 31 46](https://cloud.githubusercontent.com/assets/1480677/7612864/5f11568a-f95b-11e4-8adb-f60571d54d48.png)
