### ISSUE TITLE
Demo page is outdated

### ISSUE THREAD

**Issue by mohd-akram** [cbracco/html5-test-page#57]
It seems the demo page currently uses the gh-pages branch, which is outdated. GitHub now lets you deploy Pages from any branch. I would recommend changing the Pages branch to master in Settings->Pages so that the demo site is always up-to-date.

**Comment by Gitoffthelawn** [comment]
Seems like an excellent suggestion.

**Comment by paulocoutinhox** [comment]
Yes, will be nice.

**Comment by cbracco** [comment]
@mohd-akram thanks for the suggestion! i made the change 😄
