### ISSUE TITLE
Make a gh-pages branch

### ISSUE THREAD

**Issue by johnpolacek** [cbracco/html5-test-page#6]
I was going to make my own html test page, then I thought to myself someone else must have done this. Thanks @cbracco 

You could have a gh-pages branch so it is more findable by search engines and so people can preview it before cloning or downloading. http://cbracco.github.io/html5-test-page/

**Comment by cbracco** [comment]
@johnpolacek great idea! Done and done.

http://cbracco.github.io/html5-test-page/
