### ISSUE TITLE
Suggestions: iframe url, viewport scaling

### ISSUE THREAD

**Issue by kmturley** [cbracco/html5-test-page#8]
Some suggestions for the template:
- google.com has an security policy error within an iframe. Suggest using http://www.wikipedia.com instead

The header you could add code to set the default scale:

```
<meta name="viewport" content="width=device-width,initial-scale=1" />
```

**Comment by cbracco** [comment]
I've made both of these changes as [0.5.0](https://github.com/cbracco/html5-test-page/releases/tag/0.5.0). the iframe now points to itself (`index.html`).

Thanks for the suggestions!

**Comment by kmturley** [comment]
Awesome, thanks for making such a useful template!
